<?php
/**
 * arbit view handler
 *
 * This file is part of arbit.
 *
 * arbit is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3 of the License.
 *
 * arbit is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with arbit; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @package Core
 * @subpackage View
 * @version $Revision: 1236 $
 * @license http://www.gnu.org/licenses/gpl-3.0.txt GPL
 */

/**
 * View handler, which receives a request object containing the properties of
 * the initial request and the mixed stuff generated by the crontroller to be
 * displayed. Based on this information the view handler should select the
 * correct views, execute and echo them.
 *
 * @package Core
 * @subpackage View
 * @version $Revision: 1236 $
 * @license http://www.gnu.org/licenses/gpl-3.0.txt GPL
 */
abstract class arbitViewHandler
{
    /**
     * Request object, containing the request properties.
     *
     * @var arbitRequest
     */
    protected $request;

    /**
     * Construct view handler from reuqest object.
     *
     * Construct view handler from reuqest object.
     *
     * @ignore
     * @param arbitRequest $request
     * @return void
     */
    public function __construct( arbitRequest $request )
    {
        $this->request = $request;
    }

    /**
     * Set view locale
     *
     * Set the view locale to the given locale string.
     *
     * @param string $locale
     * @return void
     */
    abstract public function setLocale( $locale );

    /**
     * Display controller result
     *
     * Select the view, which should be used to display the controller results,
     * process and echo the view results.
     *
     * @param arbitDecorateable $model
     * @return void
     */
    abstract public function display( arbitDecorateable $model );
}

